# Generated by Django 3.2.7 on 2021-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=30)),
                ('lcompany', models.CharField(max_length=30)),
                ('lram', models.IntegerField()),
                ('lrom', models.IntegerField()),
                ('lprocessor', models.CharField(max_length=30)),
                ('lweight', models.FloatField()),
            ],
        ),
    ]
